$(document).ready(function(){
    $("#books").click(function(){
        $("#bookdesc").slideToggle("slow");
    });
    $("#games").click(function(){
        $("#gamedesc").slideToggle("slow");
    });
    $("#music").click(function(){
        $("#musicdesc").slideToggle("slow");
    });
});